### ISSUE TITLE
Important features in ygopro 2 we want to see in this project

### ISSUE THREAD

**Issue by egycno** [WolcenSykes/YGOTzolkin#2]
The most important features in ygopro 2 that we want to have in this project:
 1- The possibility to change the dimensions of the cards images by dragging them with the mouse pointer as in ygopro 2. 
2- The ability to change textures and replace them with external files or other pictures, such as card images 
3- Ability to use cards.cdb files, cards lua script files and translation files, which are used by all versions of ygopro
  4- link summons 
5- Ability to use offline AI (enable the use of offline AI even if it does not work as it should, so that users can create and test their ai.lua files) 
6- FX animations  like activating card effects , special summons, fusion summon ...  tribute, card destruction .....(It is not a problem if it is different from that in ygopro 2, I think you will create better ones)
 7- ability to use closeup hologram images (such as in google play game yugioh duel links if possible) 
8- 3D duel field
Some phrases copied from websites about the features of ygopro 2 (which we hope to see in this project)"To clarify more":
"I do like the pseudo-hologram images that float above the cards."
https://www.reddit.com/r/yugioh/comments/5fb5cw/new_ygo_pro_2_platform_is_now_available_link_in/
"You can customize the game to your liking; players are able to modify game textures, sounds and card pictures."
"Monster 3D Projections
Scaleable UI (card pictures, field, etc.)
3D animations for attacks, summons, and other miscellaneous (can be toggled on/off)
Ability to look at graveyard, banished zone, and extra deck at any time."
https://duelistsunite.org/forum/files/file/8-ygopro-2-with-updater/
 I know this is a lot but I am sure you can create a very cool and Amazing version of 3d ygopro

**Comment by WolcenSykes** [comment]
Well, it seems most of those features mentioned above were already implemented by ygopro 2, except the offline AI things.
One thing for sure, it would be totally open sourced, nothing would be like YGO Omega.
The truth is I don't really want it to be too similar to ygopro 2, or this thing won't be meaningful, why would I reinvent ygopro 2? Besides, due to many unexpected reasons, currently I don't have too much time to spare on this project, so it will take a long time to see the first release. 
Thanks for your expectation, if you are seeking for the latest ygopro 2, it's [here](url=https://github.com/mercury233/ygopro2).
